title: Paul Iacomi
email: mail@iacomipaul.com
author: Paul Iacomi
description: >- # this means ignore newlines
  Paul Iacomi is a researcher studying gas adsorption in novel materials. 
  His EU-funded PhD focused on the impact of defects in Metal Organic 
  Frameworks as part of project DEFNET. He is now a postdoctoral
  researcher at ICGM. He also drinks too much coffee.

baseurl: ""
url: "https://pauliacomi.github.io"
google_analytics: UA-56200536-1
show_excrepts: false

# social links
linkedin_username: pauliacomi
twitter_username: iacomip
github_username:  pauliacomi

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-email-protect

navigation:
  - item: "About"
    link: "/about/"
  - item: "Research"
    link: "/projects/"
  - item: "Resume"
    link: "/CV.pdf"
  - item: "Software"
    link: "/software/"
  - item: "Thoughts"
    link: "/posts/"
