title: Paul Iacomi
email: iacomi.paul@gmail.com
author: Paul Iacomi
description: >- # this means ignore newlines
  Paul Iacomi is a chemical engineer with a PhD in the 
  field of gas adsorption. His EU-funded research focused on
  the impact of defects in Metal Organic Frameworks as part of project 
  DEFNET. He is currently pursuing a career in industry.

baseurl: "/"
url: "https://www.pauliacomi.com"
google_analytics: UA-56200536-1
show_excrepts: false

# social links
linkedin_username: pauliacomi
twitter_username: i0_stream
github_username:  pauliacomi

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-email-protect

navigation:
  - item: "About"
    link: "/about/"
  - item: "Projects"
    link: "/projects/"
  - item: "Resume"
    link: "/CV.pdf"
  - item: "Thoughts"
    link: "/posts/"