title: Paul Iacomi
email: iacomi.paul@gmail.com
author: Paul Iacomi
description: >- # this means ignore newlines
  A site I created to serve as a resume and outlet for random thoughts.
baseurl: ""
url: "https://www.pauliacomi.com"
google_analytics: UA-56200536-1

# social links
linkedin_username: pauliacomi
twitter_username: i0_stream
github_username:  pauliacomi

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-email-protect

navigation:
  - item: "About"
    link: "/about/"
  - item: "Projects"
    link: "/projects/"
  - item: "Resume"
    link: "/CV.pdf"
  - item: "Blog"
    link: "/posts/"