# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Basic site settings ###################################################

title: Dr. Paul IACOMI
email: mail@pauliacomi.com
author: Paul Iacomi
description: >- # this means ignore newlines
  Dr. Paul IACOMI is a researcher studying gas adsorption in novel materials. His
  research previously focused on sorption in novel porous materials like Metal
  Organic Frameworks (MOFs). He now designs sorption instruments at Surface
  Measurement Systems. He also drinks too much coffee.

baseurl: ""
url: "https://pauliacomi.com"

# Jekyll settings #######################################################

# this tells jekyll to include the content of the _pages
# folder when generating the static site
include:
  - _pages

# options for SASS (compiled CSS)
sass:
  # source folder
  sass_dir: _sass
  # when compiling, minimize size
  style: compressed

### ! these cannot be changed for Github pages ! ###

# index for related posts
lsi: false
# disable custom plugins
safe: true
# markdown conversion
markdown: kramdown
# highlighting for text and code
highlighter: rouge
# build only pages that changed
incremental: false

### ! these can be changed ! ###

# show excerpts from posts on the news page
show_excerpts: true

# Jekyll plugins go here
plugins:
  # generate a <head> tag for SEO automatically
  - jekyll-seo-tag
  # generates an rss feed from posts and news
  - jekyll-feed
  # generates a sitemap automatically
  - jekyll-sitemap
  # autoformats publications
  - jekyll-scholar
  
# Custom settings #######################################################

# social/analytics variables
logo: "/assets/images/me.jpg"
google_analytics: G-D36S1ZFMNK
linkedin_username: pauliacomi
twitter_username: iacomip
github_username:  pauliacomi
google_scholar: 4_E8rqcAAAAJ
orcid: 0000-0001-5477-1503

# Nav
navigation:
  - item: "About"
    link: "/about/"
  - item: "Research"
    link: "/academic/"
  - item: "Resume"
    link: "/assets/downloads/CV_IACOMI.pdf"
  - item: "Software"
    link: "/software/"
  - item: "Thoughts"
    link: "/posts/"

scholar:
  style: apa
  sort_by: year,month
  order: descending
  group_by: year
  group_order: descending
